### ISSUE TITLE
v 0.12 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by doomedraven** [nfx/slrp#36]
fails on both linux and macosx

tried to run as and no extra logs:
SLRP_LOG_LEVEL=DEBUG ./slrp
SLRP_LOG_LEVEL=TRACE ./slrp

```
10:40AM INF blacklisted error="dial socks: socks4 dial: dial tcp addr:port: connect: connection refused" idx=20 proxy=socks4://217.198.181.50:49582 source=reverify
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x14b5909]

goroutine 258489 [running]:
github.com/bdandy/go-socks4.socks4.Dial.func1()
	/home/runner/work/slrp/slrp/vendor/github.com/bdandy/go-socks4/socks4.go:73 +0x29
github.com/bdandy/go-socks4.socks4.Dial({0xc004e22fc0?, {0x1b15d60?, 0x212f428?}}, {0x1825e92?, 0x90?}, {0xc000a3e550, 0xf})
	/home/runner/work/slrp/slrp/vendor/github.com/bdandy/go-socks4/socks4.go:85 +0x114d
github.com/nfx/slrp/pmux.dialProxiedConnection({0x1b19af0, 0xc001cf6d80}, {0x1825e92, 0x3}, {0xc000a3e550, 0xf})
	/home/runner/work/slrp/slrp/pmux/proxy.go:175 +0x177
net/http.(*Transport).customDialTLS(0xc006d8cbd0?, {0x1b19af0?, 0xc001cf6d80?}, {0x1825e92?, 0xc0000960f0?}, {0xc000a3e550?, 0x0?})
	/opt/hostedtoolcache/go/1.18.8/x64/src/net/http/transport.go:1317 +0x50
net/http.(*Transport).dialConn(0xc0003ca640, {0x1b19af0, 0xc001cf6d80}, {{}, 0x0, {0x18371af, 0x5}, {0xc000a3e550, 0xf}, 0x0})
	/opt/hostedtoolcache/go/1.18.8/x64/src/net/http/transport.go:1583 +0x3ff
net/http.(*Transport).dialConnFor(0x1174e8a?, 0xc0048b6370)
	/opt/hostedtoolcache/go/1.18.8/x64/src/net/http/transport.go:1449 +0xb0
created by net/http.(*Transport).queueForDial
	/opt/hostedtoolcache/go/1.18.8/x64/src/net/http/transport.go:1418 +0x3d2
```

**Comment by nfx** [comment]
Thank you for the bug report! Currently, the team operates in a limited capacity, carefully prioritizing, and we cannot provide a timeline to implement this feature. Please make a Pull Request if you'd like to see this feature sooner, and we'll guide you through the journey.

**Comment by nfx** [comment]
@doomedraven it'll be great if we can reproduce this issue. Theoretically, we have the fix at https://github.com/bdandy/go-socks4/pull/2, but it's a bizarre one - conns usually are not nil if errors are present.
